### ISSUE TITLE
Updating GitHub-hosted plugin changes folder name

### ISSUE THREAD

**Issue by verdonv** [AyeCode/wp-easy-updates#4]
Hi,

Overall, pretty cool and thank you!

I used it today for the first time to update a plugin from a GitHub repo. Although this basically worked, it did change the name of the plugin's directory in the Wordpress install, which de-activated the plugin and put an error message on the plugin's page, about the plugin main file not being found. Although this would not be a big issue on a single install, it was a bit of a pain to go through 50 or 60 sites on a multisite install, to try to discover where the plugin had been activated, and re-activate it. 

I would consider this a bug, or at least a surprise! 

Is this going to happen every time I use the update? Is the folder name change a one-time thing? The plugin folder was named 'vv-nubranding' and 'verdonv-vv-nubranding-c482f5b' after the update. FYI... this also happened with WP Easy Updates itself, with the folder name changing from 'wp-easy-updates' to 'AyeCode-wp-easy-updates-33ac445' after updating it.

Thanks,
v

**Comment by Stiofan** [comment]
Hello,

I have seen this happen sporadically but not consistently, i will try and track it down and update you here.

Thanks,

Stiofan

**Comment by verdonv** [comment]
Let me know if I can provide any info to help.

**Comment by Stiofan** [comment]
in my tests i could never repeatedly make it happen, if you find a way let me know :)

I was just using WPEU as an example and simply editing the version number to make it lower so it thinks it needs an update.

**Comment by verdonv** [comment]
I'll try to get a sandbox setup this afternoon, and see if I can reproduce it consistently.

**Comment by verdonv** [comment]
I think I've figured this out. At least, I've been able to reproduce consistent results in a couple tests.

If I update the plugin by clicking on the update link in the list of all plugins, the plugin folder name stays as it should. If I update by clicking on the link/button in the update info pane, the plugin's folder name is changed.

There are further consequences in a multisite installation. If the plugin is network activated, and the folder name gets changed, everything reactivates fine. If the plugin is not network activated, you are presented with a button to 'network activate' when the update is done. Of course you would not always want to do this. The plugin then has to be manually activated in any sites where it was activated (because they can no longer find the plugin's main file).

![screen shot 2018-05-18 at 3 28 15 pm](https://user-images.githubusercontent.com/5149763/40254455-8a7235e6-5ab1-11e8-8f76-3f92c8386f1b.png)

![screen shot 2018-05-18 at 3 28 40 pm](https://user-images.githubusercontent.com/5149763/40254475-a46bb94a-5ab1-11e8-941e-10e8b9fe3b24.png)

**Comment by verdonv** [comment]
I just tried one test doing the update via Infinite Wordpress, and that seemed to be fine. So far in my tests, the one action that seems to consistently lead to the folder being renamed is in the second screenshot above.

**Comment by Stiofan** [comment]
Thanks for the feedback/research, this is great!
I'm gona be knee deep in GDPR changes this week for my other plugins but i will get to this next week.

Thanks,

Stiofan

**Comment by Stiofan** [comment]
Thanks for your help with this, i managed to track down the problem and i have fixed it and released a new ver to resolve.

Thanks,

Stiofan

**Comment by verdonv** [comment]
Happy to have been able to help with this. I was away for a few days, but will kick the tires of this release today. I'll also try to do some theme updates... have been only trying plugins until now.
