### ISSUE TITLE
When website/db is transaferred to another domain, license should become inactive

### ISSUE THREAD

**Issue by pol76** [AyeCode/wp-easy-updates#6]
Hi,

one of the most recurring support request about updates is the "unauthorized error". 99% of the time, the licenses have been activated through the staging site and when the site is published under the final domain, the license appear as active even if they are not on our side.

 When transferring the database to a new domain, we should find a way to show the licenses as inactive, or activate them automatically on our side.

Thanks

**Comment by Stiofan** [comment]
Thinking about it the best way to handel this might be to send the licence key with the update request if present, and then return the licence info if present and update it in the DB,

We can then use this to show notifications to the user, warning them its expired or for the wrong domain.

The other option would be to add a "check licence" button next to the licence input.

**Comment by alexrollin** [comment]
To this point, it would be nice to have support for common domain names so that users can plan ahead like

stage
dev
test
staging

If they activate on any of those domains, then the prod should work automatically.

**Comment by pol76** [comment]
I think this is solved thanks to AyeCode Connect... @alexrollin do we still get support requests about this?

**Comment by alexrollin** [comment]
We still get 1 or 2 a week that change the domain name, like moving from a subdomain ro a full domain, but 9/10 signing into AC again fixes it so yes, I would say this is no longer a big issue.

Is it possible AC should sign itself out or refresh when the domain changes? Would that inprove things for the user, if they didn't have to take that step? Maybe AC should disconnect and set a dismissable notification to reconnect?

**Comment by pol76** [comment]
@stiofan?

**Comment by Stiofan** [comment]
hmm, this should already be the case, if u see somewhere where its not working please let me know.
![Screenshot from 2022-05-06 09-25-18](https://user-images.githubusercontent.com/10433311/167095672-cf493dd3-18d9-4744-94c0-bbbece2e55f5.png)

**Comment by alexrollin** [comment]
Awesome! I hadn't seen that, excellent.

**Comment by Stiofan** [comment]
i'll close this for now, @alexrollin if u see any issues in the wild then ping me or flag it for me.
